name: Webhook Data Pipeline CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------------
    # Checkout repository
    # -----------------------------------
    - name: Checkout source
      uses: actions/checkout@v4

    # -----------------------------------
    # Setup Python
    # -----------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # -----------------------------------
    # Install dependencies & lint
    # -----------------------------------
    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r notifications/requirements.txt

    - name: Run linting
      run: |
        flake8 lambda1 --max-line-length=120
        flake8 lambda2 --max-line-length=120

    # -----------------------------------
    # Package Lambda
    # -----------------------------------
    - name: Build Lambda ZIP
      run: |
        zip -r lambda1/lead_processor.zip .
        zip -r lambda2/webhook_ingestion.zip .

    # -----------------------------------
    # Configure AWS Credentials
    # -----------------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}    

    # -----------------------------------
    # Deploy CloudFormation Stack
    # -----------------------------------
    - name: Deploy Infrastructure
      run: |        
        
        aws cloudformation delete-stack --stack-name crm-lead-system --region us-west-1

        aws cloudformation wait stack-delete-complete --stack-name crm-lead-system --region us-west-1

        aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET }} 2>/dev/null || \
        aws s3api create-bucket \
        --bucket "${{ secrets.S3_BUCKET }}" \
        --region "${{ secrets.AWS_REGION }}" \
        --create-bucket-configuration LocationConstraint="${{ secrets.AWS_REGION }}"        
    
    # -----------------------------------
    # Upload Lambda ZIP to S3
    # -----------------------------------
    - name: Upload Lambda package
      run: |
        aws s3 cp lambda1/lead_processor.zip s3://${{ secrets.S3_BUCKET }}/lambda1/lead_processor.zip
        aws s3 cp lambda2/webhook_ingestion.zip s3://${{ secrets.S3_BUCKET }}/lambda2/webhook_ingestion.zip

        aws cloudformation validate-template \
          --template-body file://notifications/infrastructure/cloudformation.yaml
          
        aws cloudformation deploy \
          --stack-name crm-lead-system \
          --template-file notifications/infrastructure/cloudformation.yaml \
          --parameter-overrides LeadDataBucket=${{ secrets.S3_BUCKET }} \
          --capabilities CAPABILITY_NAMED_IAM
    
          
